-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 14:40:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demo1` ;

-- -----------------------------------------------------
-- Table `demo1`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`address` (
  `id` BIGINT NOT NULL,
  `district` VARCHAR(255) NOT NULL,
  `ward` VARCHAR(255) NOT NULL,
  `injection_site` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`category_vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`category_vaccine` (
  `id` BIGINT NOT NULL,
  `code` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`customer` (
  `id` BIGINT NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `gender` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `identification` VARCHAR(255) NOT NULL,
  `health_insurance_number` VARCHAR(255) NOT NULL,
  `occupation` VARCHAR(255) NOT NULL,
  `ethnic` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`vaccine` (
  `id` BIGINT NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `expriration_date` DATETIME NOT NULL,
  `manufacturing_date` DATETIME NOT NULL,
  `producer` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `category_vaccine_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaccine_category_vaccine1_idx` (`category_vaccine_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_category_vaccine1`
    FOREIGN KEY (`category_vaccine_id`)
    REFERENCES `demo1`.`category_vaccine` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`injection_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`injection_calendar` (
  `id` BIGINT NOT NULL,
  `injection_date` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `vaccine_id` BIGINT NOT NULL,
  `address_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_injection_calendar_vaccine1_idx` (`vaccine_id` ASC) VISIBLE,
  INDEX `fk_injection_calendar_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_injection_calendar_vaccine1`
    FOREIGN KEY (`vaccine_id`)
    REFERENCES `demo1`.`vaccine` (`id`),
  CONSTRAINT `fk_injection_calendar_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `demo1`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`injection_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`injection_history` (
  `id` BIGINT NOT NULL,
  `injection_date` DATETIME NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `number_injection` BIGINT NOT NULL,
  `vaccine_name` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `customer_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_injection_history_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_injection_history_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `demo1`.`customer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`injection_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`injection_registration` (
  `id` BIGINT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `number_injection` BIGINT NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `customer_id` BIGINT NOT NULL,
  `injection_calendar_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_injection_registration_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_injection_registration_injection_calendar1_idx` (`injection_calendar_id` ASC) VISIBLE,
  CONSTRAINT `fk_injection_registration_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `demo1`.`customer` (`id`),
  CONSTRAINT `fk_injection_registration_injection_calendar1`
    FOREIGN KEY (`injection_calendar_id`)
    REFERENCES `demo1`.`injection_calendar` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`news` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  `customer_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `demo1`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`user_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `administrator` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `created_user_id` BIGINT NULL DEFAULT NULL,
  `deleted` BIGINT NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  `modified_user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo1`.`user_group_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo1`.`user_group_relation` (
  `user_id` BIGINT NOT NULL,
  `user_group_id` BIGINT NOT NULL,
  INDEX `FK7l0smde9t1l5axg6e8jnhjrau` (`user_group_id` ASC) VISIBLE,
  INDEX `FK3ukft2xhw6af1j92qsl8y00et` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK3ukft2xhw6af1j92qsl8y00et`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo1`.`user` (`id`),
  CONSTRAINT `FK7l0smde9t1l5axg6e8jnhjrau`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `demo1`.`user_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
